# The first model in this block can be overridden
# in the command line by using:
# --model, --exp, --source, --outputdir, --catalog

datasets:
  - catalog: null
    model: 'IFS-NEMO'
    exp: 'historical-1990'
    source: 'lra-r100-monthly'
    startdate: null
    enddate: null

references:
  - catalog: obs
    model: 'ERA5'
    exp: 'era5'
    source: 'monthly'
    startdate: '1990-01-01'
    enddate: '2020-12-31'
  - catalog: obs
    model: 'CERES'
    exp: 'ebaf-toa41'
    source: 'monthly'
    regrid: 'r100'
    startdate: '2000-01-01'
    enddate: '2020-12-31'

setup:
  loglevel: 'WARNING'

output:
  outputdir: "./"
  rebuild: true
  save_netcdf: true
  save_pdf: true
  save_png: true
  dpi: 300

diagnostics:
  boxplots:
    run: true
    diagnostic_name: 'radiation'
    variables:  ['-tnlwrf', 'tnswrf']
